name: 'Blogs Cross-Post Action for Teams'
description: 'GitHub action for teams to easily cross-post blog article on dev.to, Hashnode and Medium.'
author: '@ommyjay'
inputs:
  files_location:
    required: true
    description: 'articles files location'
    default: 'posts/**/*.md'
  publish:
    required: true
    description: 'publish articles by default'
    default: 'false'
  devto_api_key:
    required: true
    description: 'author dev to api key'
  devto_org_id:
    required: true
    description: 'devto org id'
  ghub_token:
    required: true
    description: 'ghub token'
  commiting_branch:
    required: true
    description: 'commiting branch'
runs:
  using: 'node16'
  main: 'dist/index.js'
